### ISSUE TITLE
Support all ESDT

### ISSUE THREAD

**Issue by PABourdais** [xdevguild/esdt-and-egld-airdrop-scripts#1]
@PaulHendi I am sure we can add support for all the ESDT 👍

**Comment by PaulHendi** [comment]
@PABourdais Thanks for pointing this out. Yes I'll include a similar script for regular ESDT tokens :)

**Comment by PaulHendi** [comment]
I included a script for classical ESDT airdrop. Tested with Golden token, it works :)
